// This file is not used when using generateSW strategy
// The service worker is automatically generated by Workbox
// But we keep this file for potential future customizations

self.addEventListener('install', function(event) {
    console.log('Service Worker installing.');
});

self.addEventListener('activate', function(event) {
    console.log('Service Worker activating.');
});

self.addEventListener('fetch', function(event) {
    // Log only in development to avoid console spam
    if (self.location.hostname === 'localhost') {
        console.log('Service Worker fetching:', event.request.url);
    }
});