// This file is not used when using generateSW strategy
// The service worker is automatically generated by Workbox
// But we keep this file for potential future customizations

self.addEventListener('install', function(event) {
    // Service Worker installing
});

self.addEventListener('activate', function(event) {
    // Service Worker activating
});

self.addEventListener('fetch', function(event) {
    // Service Worker fetch handler
});